# ─────────────────────────────────────────────────────────
# OmicsVisor - Documentation Module
# Author: Oliver Popp
# ─────────────────────────────────────────────────────────
documentation_ui <- function(id) {
  ns <- NS(id)
  tagList(
      titlePanel("Documentation"),
      
      h2("OmicsVisor Tool Overview"),
      p("OmicsVisor is a Shiny-based, interactive exploration tool developed to facilitate browsing and visualisation of processed proteomics data from the MDC Proteomics Platform. 
         It is designed to be usable also by collaborators without bioinformatics training, enabling exploratory data analysis, hypothesis generation and candidate prioritisation."),
      
      p("OmicsVisor reads the standard-format data frames (Excel or tab-delimited text files) that accompany reports sent out by the Proteomics Platform. 
         Please note that the tool is currently in its beta phase and several modules were implemented with the help of ChatGPT. 
         For this reason, plots and tables generated by the tool should not be treated as publication-ready figures without prior discussion and verification with the MDC Proteomics Platform. 
         The tool is intended as a powerful, flexible interface for exploratory analysis."),
      
      h3("Author"),
      p("This tool was developed by Oliver Popp (MDC Proteomics Platform). For inquiries, feedback or feature requests, please contact ",
        tags$a(href = "mailto:oliver.popp@mdc-berlin.de", "oliver.popp@mdc-berlin.de"), "."),
      
      h3("General Usage Workflow"),
      p("Most OmicsVisor modules operate on a loaded data frame. Exceptions are modules such as the Venn Diagram, Regex Tool and some list-based utilities, which can operate independently of the loaded data."),
      
      h4("1. Load Data"),
      p("Start by loading a tab-delimited '.txt' file or an Excel file (OmicsVisor uses the first sheet). 
         The MDC Proteomics Platform provides a standardised table format; if you encounter issues loading the data, please get in touch."),
      
      h4("2. Core Columns Used by OmicsVisor"),
      tags$ul(
        tags$li(strong("ID column: "), "The first column (named ", code("id"), ") must contain a unique identifier per row (e.g. GeneSymbol_UniprotIdentifier)."),
        tags$li(strong("Statistical columns: "), "Pairwise comparisons are encoded as ",
                code("logFC_"), " columns (effect sizes) and their corresponding ",
                code("adj.P.Val_"), " columns (Benjamini-Hochberg adjusted p-values). 
                A comparison name such as ", code("conditionA.over.conditionB"),
                " means that condition A is in the numerator and condition B is in the denominator. 
                If you need the ratio inverted, please ask for a modified input table.")
      ),
      
      h4("3. Intensity Column Regex (Global Setting)"),
      p("The ", strong("Intensity column regular expression"), " determines which columns are treated as intensity values in the Heatmap, PCA and Boxplot modules. 
         The default is ", code("^Intensity"), ", meaning all columns that start with “Intensity”."),
      p("The standard output tables usually contain both ", code("Intensity_"), " and ", code("Imputed_"), " columns. 
         The ", code("Imputed_"), " columns (if present) are typically the values used for statistical analysis (two-sample moderated t-tests via limma) and form a complete matrix without missing values."),
      p("Recommendations:"),
      tags$ul(
        tags$li("For ", strong("Heatmap"), " and ", strong("PCA/UMAP"), " it is preferable to use imputed intensities, as clustering and dimensionality reduction benefit from complete matrices."),
        tags$li("For the ", strong("Boxplot"), " module (including crossbar plots), non-imputed intensities are often more appropriate, especially when groups have ", code("n ≤ 4"), " replicates.")
      ),
      
      h3("Module Descriptions"),
      
      h4("Data Overview Module"),
      p("The ", strong("Data Overview"), " module displays the full loaded data frame in a searchable, filterable table. 
         You can adjust the number of rows displayed, scroll through all columns and search for specific protein names, gene symbols or other patterns (including regular expressions)."),
      
      h4("Volcano Plot Module"),
      p("The ", strong("Volcano Plot"), " module visualises two-sample comparisons, showing effect size (", code("logFC"), ") versus significance (", code("adj.P.Val"), "). 
         When you select a ", code("logFC_"), " column, the corresponding ", code("adj.P.Val_"), " column is matched automatically; nonetheless, it is good practice to verify that these pairs are correct."),
      p("You can:"),
      tags$ul(
        tags$li("Adjust ", strong("adj.P.Val cutoff"), " and ", strong("logFC cutoff"), ". As a general recommendation, an ", code("adj.P.Val ≤ 0.05"), " is useful for significance, and either ", code("|logFC| ≥ 1"), " for strong effects or ", code("logFC = 0"), " if you want to see all significant candidates at the chosen p-value cutoff."),
        tags$li("Click data points to display user-chosen labels (e.g. ", code("id"), ", number of peptides)."),
        tags$li("Generate ID lists for left, right or both sides of the volcano based on your cutoffs, and copy them for downstream use.")
      ),
      p("These ID lists can be reused in the Heatmap, PCA, Volcano Printer and other modules."),
      
      h4("Volcano Printer Module"),
      p("The ", strong("Volcano Printer"), " module extends the Volcano Plot by enabling export of vector-based PDF plots that are closer to publication quality. 
         As in the Volcano Plot module, ", code("logFC_"), " and ", code("adj.P.Val_"), " columns are paired automatically, and thresholds are set in log2 space (e.g. |log2FC| = 1 corresponds to a 2-fold change)."),
      p("You can select one or more label columns and optionally restrict labels to IDs meeting the cutoff criteria. 
         Use the download button to export the volcano plot as a PDF for further refinement."),
      
      h4("Donut Plot Module"),
      p("The ", strong("Donut Plot"), " module applies ", strong("global cutoffs"), " for ", code("logFC"), " and ", code("adj.P.Val"), " across all comparisons and summarises the number of up- and downregulated hits per comparison as donut charts."),
      p("You can:"),
      tags$ul(
        tags$li("Set a global ", code("logFC"), " cutoff and a global ", code("adj.P.Val"), " cutoff."),
        tags$li("Select up- and/or downregulated hits per comparison."),
        tags$li("Identify overlapping candidates across comparisons (within a comparison, selection is OR; across comparisons, overlap essentially behaves like AND).")
      ),
      
      h4("UpSet Plot Module"),
      p("The ", strong("UpSet Plot"), " module provides an overview of how many IDs are significant in each comparison at the chosen global cutoffs and how many are shared between comparisons. 
         It is particularly useful when you have more than one pairwise comparison and want to understand intersection patterns beyond simple Venn diagrams."),
      
      h4("Heatmap Module"),
      p("The ", strong("Heatmap"), " module allows you to visualise intensity values across samples for all features or for a selected subset of IDs."),
      p("Key options:"),
      tags$ul(
        tags$li("Paste a comma-separated list of IDs into “manually select IDs” to focus on a subset of interest (e.g. significant hits from a volcano plot)."),
        tags$li("Select intensity columns filtered by the global Intensity Regex (or all columns if the regex is blank)."),
        tags$li("Choose a row-name column (e.g. ", code("Genes"), ", ", code("id"), ") for heatmap labelling."),
        tags$li("Optionally apply feature-wise z-scoring to enhance contrast across samples."),
        tags$li("Decide whether to cluster rows and/or columns."),
        tags$li("Export the underlying matrix as a tab-delimited '.txt' file for further analysis.")
      ),
      
      h4("PCA Module"),
      p("The ", strong("PCA"), " module performs principal component analysis (and UMAP-based dimensionality reduction) on selected intensity columns."),
      p("You can:"),
      tags$ul(
        tags$li("Use the global Intensity Regex to define candidate intensity columns for PCA."),
        tags$li("Choose between using all rows or a manually entered comma-separated ID list."),
        tags$li("Define grouping / colour annotation by splitting intensity column names into components to extract group labels."),
        tags$li("Switch between PCA and UMAP and adjust parameters such as scaling/centering for PCA and neighbours/min_dist for UMAP."),
        tags$li("Export the underlying PCA/UMAP coordinates for downstream use and choose between different colour palettes.")
      ),
      
      h4("Boxplot Module"),
      p("The ", strong("Boxplot"), " module allows visualisation of intensity distributions per group or sample, including crossbar plots. 
         This is particularly useful when you want to inspect raw (non-imputed) intensities and when group sizes are small (e.g. ", code("n ≤ 4"), ")."),
      
      h4("Venn Diagram Module (VennDi)"),
      p("The ", strong("VennDi"), " module operates independently of the loaded data. 
         It compares two or more comma-separated lists of identifiers and reports unique and overlapping subsets, which you can copy for downstream use. 
         This is helpful for quickly combining or contrasting ID lists generated in OmicsVisor or external tools."),
      
      h4("ID List Generator Module"),
      p("The ", strong("ID List Generator"), " module lets you start from gene symbols and find corresponding IDs in the loaded table (e.g. from a ", code("Genes"), " column). 
         You can:"),
      tags$ul(
        tags$li("Paste a list of gene symbols (search is case-sensitive)."),
        tags$li("Search for matching entries in a gene-related column (e.g. ", code("Genes"), ")."),
        tags$li("Copy the resulting ID list for use in other modules."),
        tags$li("Browse and search ", code(".gmt"), " files to extract gene sets and convert them into ID lists.")
      ),
      
      h4("Regex Tool Module"),
      p("The ", strong("Regex Tool"), " module helps convert IDs back to gene names or extract portions of identifiers using regular expressions. 
         For example, if IDs are of the form ", code("GeneSymbol_UniprotIdentifier"), " you can extract just the gene symbol for downstream enrichment tools such as Metascape. 
         The module can also deduplicate output to provide unique lists."),
      
      h4("logFC Scatter Plot Module"),
      p("The ", strong("logFC Scatter Plot"), " module allows direct comparison of two pairwise comparisons (e.g. ", code("treatment1.over.control"), " vs ", code("treatment2.over.control"), "). 
         It displays the correlation of logFC values, highlights shared vs unique significant hits and allows you to mark specific IDs of interest. 
         Overlapping and non-overlapping candidate lists can be curated in combination with the Donut and VennDi modules."),
      
      h4("GCT Export Module and 1D Enrichment Module"),
      p("As a downstream analysis step, the ", strong("GCT Export"), " module lets you export the processed data as a ", code(".gct"), " file, which can be used in external GSEA tools or together with the internal ", strong("1D Enrichment"), " module."),
      p("You can use any ", code(".gmt"), " file (e.g. downloaded from MSigDB or self-curated). 
         Please treat the 1D Enrichment results as exploratory and discuss any key findings with the Proteomics Platform."),
      
      h3("Footnote: Imputed Intensities"),
      p("Imputation is performed in a controlled manner using a left-censored approach on a pre-filtered data frame so that not too many artificial values are introduced. 
         These imputed intensities are optimised for statistical analyses (e.g. limma moderated t-tests), but should still be interpreted with appropriate caution in downstream plots."),
      
      h3("OmicsVisor Assistant"),
      p("For additional guidance on OmicsVisor usage, interpretation of results or troubleshooting, you can also consult the OmicsVisor Assistant: ",
        tags$a(href = "https://chatgpt.com/g/g-W6cUieQY1-omicsvisor-assistant", "OmicsVisor Assistant"), ".")
  )
}

documentation_server <- function(id) {
  moduleServer(id, function(input, output, session) {})
}